# 24학번 석사과정 신수경 (2024191004)

In [7]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable


In [11]:
import numpy as np

# Reading the example code

In [14]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape
(2, 3)

(2, 3)

# What is an “array”?

In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [26]:
a[0]

1

In [28]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [30]:
a[:3]

array([10,  2,  3])

In [32]:
b = a[3:]
b

array([4, 5, 6])

In [34]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [42]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
a[1, 3]

8

# Array attributes

In [47]:
a.ndim

2

In [51]:
a.shape

(3, 4)

In [53]:
len(a.shape) == a.ndim

True

In [55]:
a.size

12

In [57]:
import math
a.size == math.prod(a.shape)

True

In [59]:
a.dtype

dtype('int32')

# How to create a basic array

In [62]:
np.zeros(2)

array([0., 0.])

In [64]:
np.ones(2)

array([1., 1.])

In [66]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [68]:
np.arange(4)

array([0, 1, 2, 3])

In [70]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [72]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# Adding, removing, and sorting elements

In [75]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [77]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [81]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [85]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [88]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [90]:
array_example.ndim

3

In [92]:
array_example.size

24

In [94]:
array_example.shape

(3, 2, 4)

# Can you reshape an array?

In [105]:
a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

np.reshape(a, newshape=(1, 6), order='C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [108]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [110]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [112]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [114]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [116]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [118]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [120]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and slicing

In [137]:
data = np.array([1, 2, 3])

data[1]

2

In [135]:
data[0:2]

array([1, 2])

In [139]:
data[1:]

array([2, 3])

In [141]:
data[-2:]

array([2, 3])

In [143]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [145]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [147]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [149]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [151]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [153]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [155]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [157]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [159]:
print(a[b])

[1 2 3 4]


In [161]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# How to create an array from existing data

In [164]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [166]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [168]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [170]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [172]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [174]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [176]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [178]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [180]:
b1 = a[0, :]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [182]:
b2 = a.copy()

# Basic array operations

In [185]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [187]:
data - ones
data * data
data / data

array([1., 1.])

In [189]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [191]:
b = np.array([[1, 1], [2, 2]])

In [193]:
b.sum(axis=0)

array([3, 3])

In [195]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

In [198]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

# More useful array operations

In [201]:
data.max()
data.min()
data.sum()

3.0

In [203]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [205]:
a.sum()

4.8595784

In [207]:
a.min()

0.05093587

In [209]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# Creating matrices

In [212]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [214]:
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [216]:
data.max()
data.min()
data.sum()

21

In [218]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)
data.max(axis=1)

array([2, 5, 6])

In [220]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [222]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [224]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [226]:
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.22903099, 0.83204185, 0.12928941])

In [228]:
np.ones((3, 2))
np.zeros((3, 2))
rng.random((3, 2)) 

array([[0.75168815, 0.86732968],
       [0.78071116, 0.16470784],
       [0.46909527, 0.33213747]])

# Generating random numbers

In [231]:
rng.integers(5, size=(2, 4)) 

array([[2, 1, 4, 1],
       [3, 4, 1, 0]], dtype=int64)

# How to get unique items and counts

In [234]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [236]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [238]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [240]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [242]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [244]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [246]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [248]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


# Transposing and reshaping a matrix

In [251]:
data.reshape(2, 3)
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [253]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [255]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [257]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

In [260]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [262]:
reversed_arr = np.flip(arr)

In [264]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [266]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [268]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [270]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [272]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [274]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [276]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays

In [279]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [281]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [283]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [285]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
